apiVersion: v1
kind: Namespace
metadata:
  name: test-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-storage-store
  namespace: test-storage
spec:
  resources:
    requests:
      storage: 1G
  volumeMode: Filesystem
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: Pod
metadata:
  name: test-storage-pod
  labels:
    app.kubernetes.io/name: myapp
spec:
  volumes:
  - name: provision
    persistentVolumeClaim:
      claimName: test-storage-store
  containers:
  - name: myapp
    image: ubuntu
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: provision
      mountPath: /opt
