apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-storage-volume
spec:
  capacity:
    storage: 1G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/nfsdata
    server: 172.31.39.216

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-datastore-vol1
spec:
  resources:
    requests:
      storage: 1G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-store-app
  namespace: default
  labels:
    app.kubernetes.io/name: myapp
spec:
  volumes:
  - name: nfs-mount-path
    persistentVolumeClaim:
      claimName: nfs-datastore-vol1
  containers:
  - name: nfs-store-app
    image: ubuntu:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: 
    - sleep
    - "3000"
    volumeMounts:
    - name: nfs-mount-path
      mountPath: /opt