apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-storage-volume-database
spec:
  capacity:
    storage: 1G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/pgdata
    server: 172.31.39.216

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-datastore-vol1-database
  namespace: database
spec:
  resources:
    requests:
      storage: 1G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce