apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app1
  template:
    metadata:
      labels:
        app: example-app1
    spec:
      containers:
      - name: example-app1
        image: prateekkumawat/kubernetes:podlable
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        resources:
          requests: 
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
        command:
        - /bin/sh
        - -c
        - |
          cat <<EOF > /usr/share/nginx/html/index.html
          <!DOCTYPE html>
          <html>
          <head>
            <title>Kubernetes Pod Info</title>
          </head>
          <body style="font-family: Arial;">
            <h1>Nginx Kubernetes Test</h1>
            <p><b>Pod Name:</b> $POD_NAME</p>
            <p><b>Pod IP:</b> $POD_IP</p>
          </body>
          </html>
          EOF
          nginx -g 'daemon off;'
---
apiVersion: v1
kind: Service
metadata:
  name: example-app1-svc
spec:
  selector:
    app: example-app1
  type: NodePort  
  ports:
  - port: 80
    targetPort: 80
  