apiVersion: v1
kind: Pod
metadata:
  name: myapp1
  labels:
    app.kubernetes.io/name: myapp1
spec:
  containers:
  - name: myapp1
    image: nginx
    resources:
      requests: 
        memory: "800Mi"
        cpu: "200m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  nodeSelector: 
    type: db
    
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp2
  labels:
    app.kubernetes.io/name: myapp2
spec:
  containers:
  - name: myapp1
    image: nginx
    resources:
      requests: 
        memory: "800Mi"
        cpu: "200m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  nodeSelector: 
    type: mgmt
    
