apiVersion: v1
kind: Pod
metadata:
  name: myapp1
  labels:
    app.kubernetes.io/name: myapp1
spec:
  containers:
  - name: myapp1
    image: nginx
    resources:
      requests: 
        memory: "100Mi"
        cpu: "200m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  nodeSelector: 
    type: db
    
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp2
  labels:
    app.kubernetes.io/name: myapp2
spec:
  containers:
  - name: myapp1
    image: nginx
    resources:
      requests: 
        memory: "100Mi"
        cpu: "200m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  nodeSelector: 
    type: mgmt
    

# kubectl label node ip-172-31-34-175.ap-south-1.compute.internal type=db
# kubectl label node ip-172-31-35-80.ap-south-1.compute.internal type=mgmt
# kubectl get node --show-labels